@apiUrl = https://localhost:7018

GET {{apiUrl}}/products
Accept: application/json
Content-Type: application/json

###

GET {{apiUrl}}/products/67
Accept: application/json

###

GET {{apiUrl}}/products/products/1
Accept: application/json

###

POST {{apiUrl}}/products
Accept: application/json
Content-Type: application/json

{
  "name": "Test5",
  "description": "test product5",
  "price": 15,
  "imageUrl": "test5.jpg",
  "stock": 18,
  "createdAt": "2024-06-13T19:27:32",
  "categoryId": 2
}

###

PUT {{apiUrl}}/products/8
Accept: application/json
Content-Type: application/json

{
  "id": 8,
  "name": "Test updated",
  "description": "test product5",
  "price": 20,
  "imageUrl": "test5.jpg",
  "stock": 5,
  "createdAt": "2024-06-13T19:27:32",
  "categoryId": 1
}

###

DELETE {{apiUrl}}/products/8
Accept: application/json
Content-Type: application/json

###

GET {{apiUrl}}/category/
Accept: application/json
Content-Type: application/json

###

GET {{apiUrl}}/category/2
Accept: application/json
Content-Type: application/json

###

GET {{apiUrl}}/category/products
Accept: application/json
Content-Type: application/json

###

POST {{apiUrl}}/category
Accept: application/json
Content-Type: application/json

{
  "name": "category3",
  "imageUrl": "category3.jpg"
}

###

PUT {{apiUrl}}/category/5
Accept: application/json
Content-Type: application/json

{
  "id": 5,
  "name": "category3 updated",
  "imageUrl": "category3.jpg"
}

###

DELETE  {{apiUrl}}/category/5
Accept: application/json
Content-Type: application/json