@apiUrl = https://localhost:7018

GET {{apiUrl}}/products
Accept: application/json
Content-Type: application/json

###

GET {{apiUrl}}/products/9
Accept: application/json

###

GET {{apiUrl}}/products/products/2
Accept: application/json

###

POST {{apiUrl}}/products
Accept: application/json
Content-Type: application/json

{
  "name": "Test4",
  "description": "test product4",
  "price": 20.00,
  "imageUrl": "test4.jpg",
  "stock": 5,
  "createdAt": "2024-06-14T19:27:32",
  "categoryId": 2
}

###

PUT {{apiUrl}}/products/9
Accept: application/json
Content-Type: application/json

{
    "id": 9,
    "name": "Test4 updated",
    "description": "test product4",
    "price": 20.00,
    "imageUrl": "test4.jpg",
    "stock": 5,
    "createdAt": "2024-06-14T19:27:32",
    "categoryId": 2
}

###

DELETE {{apiUrl}}/products/9
Accept: application/json
Content-Type: application/json

###

GET {{apiUrl}}/category/
Accept: application/json
Content-Type: application/json

###

GET {{apiUrl}}/category/6
Accept: application/json
Content-Type: application/json

###

POST {{apiUrl}}/category
Accept: application/json
Content-Type: application/json

{
  "name": "category4",
  "imageUrl": "category4.jpg"
}

###

PUT {{apiUrl}}/category/6
Accept: application/json
Content-Type: application/json

{
  "id": 6,
  "name": "category4 updated",
  "imageUrl": "category4.jpg"
}

###

DELETE  {{apiUrl}}/category/4
Accept: application/json
Content-Type: application/json